nodeLinker: pnp

packageExtensions:
  ts-node@*:
    dependencies:
      typescript: "*"
  "@parcel/fs@*":
    dependencies:
      "@parcel/core": "*"
  "@parcel/workers@*":
    dependencies:
      "@parcel/core": "*"
  "@parcel/cache@*":
    dependencies:
      "@parcel/core": "*"
  "@parcel/package-manager@*":
    dependencies:
      "@parcel/core": "*"
  eslint-import-resolver-typescript@*:
    dependencies:
      eslint-plugin-import: "*"
  gatsby-plugin-gatsby-cloud@*:
    dependencies:
      webpack: "*"
  gatsby-plugin-utils@*:
    dependencies:
      graphql: "*"
  eslint-plugin-flowtype@*:
    dependencies:
      "@babel/plugin-syntax-flow": "*"  
      "@babel/plugin-transform-react-jsx": "*"  
  eslint-config-react-app@*:
    dependencies:
      babel-eslint: "*"
  "@babel/plugin-syntax-flow@*":
    dependencies:
      "@babel/core": "*"
  "@babel/plugin-transform-react-jsx@*":
    dependencies:
      "@babel/core": "*"

pnpEnableEsmLoader: true

pnpFallbackMode: dependencies-only

yarnPath: .yarn/releases/yarn-3.2.2.cjs